name: next_pass
channels:
  - conda-forge
dependencies:
  - asf_search
  - beautifulsoup4
  - boto3
  - earthaccess
  - geopandas
  - jupyterlab
  - leafmap
  - lxml
  - rasterio
  - tabulate
  - csv
